/****************************************************************************
The contents of this file are subject to the Interbase Public
License Version 1.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a copy
of the License at http://www.Inprise.com/IPL.html

Software distributed under the License is distributed on an
"AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
or implied. See the License for the specific language governing
rights and limitations under the License.

*****************************************************************************/

// Code generated by _attic/errormsgs; DO NOT EDIT.
// Source: https://raw.githubusercontent.com/FirebirdSQL/firebird/master/src/include/firebird/impl/msg/all.h

//go:generate go run ./_attic/errormsgs

package firebirdsql

// errmsgs returns the Firebird message template for a GDS error code,
// or an empty string when the code is unknown.
func errmsgs(code int) string {
	switch code {
	case 336265217:
		return "no symbol message @1\n"
	case 336265218:
		return "test error one\n"
	case 336265219:
		return "unique key violation \"@1\" on table \"@2\"\n"
	case 336265220:
		return "symbol only entry\n"
	default:
		return ""
	}
}
