/****************************************************************************
The contents of this file are subject to the Interbase Public
License Version 1.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a copy
of the License at http://www.Inprise.com/IPL.html

Software distributed under the License is distributed on an
"AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
or implied. See the License for the specific language governing
rights and limitations under the License.

*****************************************************************************/

// Code generated by _attic/errormsgs; DO NOT EDIT.
// Source: https://raw.githubusercontent.com/FirebirdSQL/firebird/master/src/include/firebird/impl/msg/all.h

package firebirdsql

// ISC* constants map Firebird symbol names to their numeric GDS error codes.
// Use with errors.As to classify *FbError values:
//
//	var fbErr *FbError
//	if errors.As(err, &fbErr) && slices.Contains(fbErr.GDSCodes, ISCUniqueKeyViolation) { ... }
const (
	// TEST facility
	ISCTestErrOne = 336265218
	ISCTestErrTwo = 336265219
	ISCTestSymOnly = 336265220
)
