/****************************************************************************
The contents of this file are subject to the Interbase Public
License Version 1.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a copy
of the License at http://www.Inprise.com/IPL.html

Software distributed under the License is distributed on an
"AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
or implied. See the License for the specific language governing
rights and limitations under the License.

*****************************************************************************/

// Code generated by _attic/errormsgs; DO NOT EDIT.
// Source: https://raw.githubusercontent.com/FirebirdSQL/firebird/master/src/include/firebird/impl/msg/all.h

package firebirdsql

// gdsToSQLCode returns the Firebird SQL error code for a GDS error code, or 0.
// Used as a fallback when the server does not send isc_arg_sqlerr.
func gdsToSQLCode(code int) int32 {
	switch code {
	case 336265218:
		return -900
	case 336265219:
		return -803
	default:
		return 0
	}
}
