/****************************************************************************
The contents of this file are subject to the Interbase Public
License Version 1.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a copy
of the License at http://www.Inprise.com/IPL.html

Software distributed under the License is distributed on an
"AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
or implied. See the License for the specific language governing
rights and limitations under the License.

*****************************************************************************/

// Code generated by _attic/errormsgs; DO NOT EDIT.
// Source: https://raw.githubusercontent.com/FirebirdSQL/firebird/master/src/include/firebird/impl/msg/all.h

package firebirdsql

// gdsToSQLState returns the SQL:2003 SQLSTATE string for a GDS error code,
// or an empty string when the code has no SQLSTATE mapping.
// Used as a fallback when the server does not send isc_arg_sql_state.
func gdsToSQLState(code int) string {
	switch code {
	case 336265218:
		return "HY000"
	case 336265219:
		return "23505"
	default:
		return ""
	}
}
