// Generator for timezonemap.go.
// Fetches Firebird's TimeZones.h and emits both switch functions plus
// getTimezoneVersion.
//
// Usage:
//
//	go run ./_attic/timezonemap                          # fetch from upstream master
//	go run ./_attic/timezonemap -url <url>               # custom branch/tag
//	go run ./_attic/timezonemap -src /path/to/TimeZones.h # local file
//	go run ./_attic/timezonemap -out /path/to/timezonemap.go
package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
)

const (
	defaultURL = "https://raw.githubusercontent.com/FirebirdSQL/firebird/master/src/common/TimeZones.h"

	licenseHeader = `/*******************************************************************************
The MIT License (MIT)

Copyright (c) 2019 Hajime Nakagami

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*******************************************************************************/
`
)

var (
	reVersion   = regexp.MustCompile(`BUILTIN_TIME_ZONE_VERSION\s*=\s*"([^"]+)"`)
	reListStart = regexp.MustCompile(`BUILTIN_TIME_ZONE_LIST\s*\[`)
	reEntry     = regexp.MustCompile(`"([^"]+)"`)
)

func main() {
	urlFlag := flag.String("url", defaultURL, "URL of Firebird TimeZones.h")
	srcFlag := flag.String("src", "", "local file path of TimeZones.h (overrides -url)")
	outFlag := flag.String("out", "timezonemap.go", "output file path")
	flag.Parse()

	var r io.ReadCloser
	if *srcFlag != "" {
		f, err := os.Open(*srcFlag)
		if err != nil {
			fmt.Fprintf(os.Stderr, "open %s: %v\n", *srcFlag, err)
			os.Exit(1)
		}
		r = f
	} else {
		resp, err := http.Get(*urlFlag)
		if err != nil {
			fmt.Fprintf(os.Stderr, "fetch %s: %v\n", *urlFlag, err)
			os.Exit(1)
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			fmt.Fprintf(os.Stderr, "fetch %s: HTTP %d\n", *urlFlag, resp.StatusCode)
			os.Exit(1)
		}
		r = resp.Body
	}
	defer r.Close()

	version, names, err := parse(r)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse: %v\n", err)
		os.Exit(1)
	}

	if err := generate(*outFlag, version, names); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s: tzdata version=%s entries=%d\n", *outFlag, version, len(names))
}

func parse(r io.Reader) (version string, names []string, err error) {
	scanner := bufio.NewScanner(r)
	inList := false
	for scanner.Scan() {
		line := scanner.Text()
		if version == "" {
			if m := reVersion.FindStringSubmatch(line); m != nil {
				version = m[1]
				continue
			}
		}
		if !inList {
			if reListStart.MatchString(line) {
				inList = true
			}
			continue
		}
		if strings.HasPrefix(strings.TrimSpace(line), "};") {
			break
		}
		if m := reEntry.FindStringSubmatch(line); m != nil {
			names = append(names, m[1])
		}
	}
	if err := scanner.Err(); err != nil {
		return "", nil, err
	}
	if version == "" {
		return "", nil, fmt.Errorf("BUILTIN_TIME_ZONE_VERSION not found in input")
	}
	if len(names) == 0 {
		return "", nil, fmt.Errorf("BUILTIN_TIME_ZONE_LIST not found or empty")
	}
	return version, names, nil
}

func generate(outPath, version string, names []string) (err error) {
	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer func() { err = errors.Join(err, f.Close()) }()

	w := bufio.NewWriter(f)

	fmt.Fprint(w, licenseHeader)
	fmt.Fprintf(w, "\n// Code generated by _attic/timezonemap; DO NOT EDIT.\n")
	fmt.Fprintf(w, "// Source: %s\n\n", defaultURL)
	fmt.Fprintf(w, "//go:generate go run ./_attic/timezonemap\n\n")
	fmt.Fprintf(w, "package firebirdsql\n\n")

	fmt.Fprintf(w, "// getTimezoneVersion returns the IANA timezone database version bundled with Firebird.\n")
	fmt.Fprintf(w, "func getTimezoneVersion() string {\n")
	fmt.Fprintf(w, "\treturn %q\n", version)
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "// getTimezoneIDByName returns the Firebird timezone ID for a given IANA timezone name.\n")
	fmt.Fprintf(w, "func getTimezoneIDByName(name string) int32 {\n")
	fmt.Fprintf(w, "\tswitch name {\n")
	for i, name := range names {
		fmt.Fprintf(w, "\tcase %q:\n\t\treturn %d\n", name, 65535-i)
	}
	fmt.Fprintf(w, "\tdefault:\n\t\treturn 0\n")
	fmt.Fprintf(w, "\t}\n}\n\n")

	fmt.Fprintf(w, "// getTimezoneNameByID returns the IANA timezone name for a given Firebird timezone ID.\n")
	fmt.Fprintf(w, "func getTimezoneNameByID(id int) string {\n")
	fmt.Fprintf(w, "\tswitch id {\n")
	for i, name := range names {
		fmt.Fprintf(w, "\tcase %d:\n\t\treturn %q\n", 65535-i, name)
	}
	fmt.Fprintf(w, "\tdefault:\n\t\treturn \"\"\n")
	fmt.Fprintf(w, "\t}\n}\n")

	return w.Flush()
}
